import { Zap, Rocket, Sparkles, Crown, Diamond } from 'lucide-react';

export const INDUSTRY_TIERS = [
  {
    id: 'foundation',
    name: 'Foundation',
    tagline: 'Learn Web3 Basics',
    price: 97,
    billing: '/month',
    priceId: 'price_1StlXNFjshJghowT3RGDE09P',
    productId: 'prod_TrUWkVj5btmw3y',
    color: 'from-slate-500 to-slate-600',
    icon: Zap,
    description: 'Perfect for businesses exploring Web3 possibilities',
    features: [
      'Web3 fundamentals education',
      'Industry-specific roadmap consultation',
      'Community Discord access',
      'Weekly group strategy calls',
      'Basic AI research assistant',
      'Email support (48hr response)',
    ],
    deliverables: [
      'Web3 readiness assessment',
      'Custom opportunity report',
    ],
    guarantee: '14-day money back',
  },
  {
    id: 'builder',
    name: 'Builder',
    tagline: 'Build Your Web3 Presence',
    price: 297,
    billing: '/month',
    priceId: 'price_1StlXPFjshJghowT0FoqZOPo',
    productId: 'prod_TrUWXYYJ49P6aB',
    color: 'from-blue-500 to-cyan-500',
    icon: Rocket,
    description: 'Launch your Web3 presence with expert guidance',
    features: [
      'Everything in Foundation',
      'Custom Web3 website design',
      'Wallet integration setup',
      'NFT gallery implementation',
      'Priority support (24hr response)',
      'Bi-weekly 1-on-1 strategy calls',
      'Smart contract templates',
    ],
    deliverables: [
      'Full Web3 website',
      'Integration documentation',
      '3-month implementation plan',
    ],
    guarantee: '30-day results or refund',
  },
  {
    id: 'accelerator',
    name: 'Accelerator',
    tagline: 'Launch NFTs & DAOs',
    price: 997,
    billing: '/month',
    priceId: 'price_1StlXRFjshJghowTdw1SrZCy',
    productId: 'prod_TrUW5h8reSBfOw',
    color: 'from-purple-500 to-pink-500',
    icon: Sparkles,
    popular: true,
    description: 'Full NFT collection and DAO governance setup',
    features: [
      'Everything in Builder',
      'Custom NFT collection design & launch',
      'Smart contract development & audit',
      'DAO governance structure',
      'Token creation & distribution',
      '24/7 AI agent support',
      'Dedicated account manager',
      'Weekly strategy sessions',
    ],
    deliverables: [
      '10,000 NFT collection ready',
      'DAO smart contracts deployed',
      'Token economics design',
      'Community building playbook',
    ],
    guarantee: 'Revenue increase or money back',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tagline: 'Complete Web3 Suite',
    price: 2997,
    billing: '/month',
    priceId: 'price_1StlXTFjshJghowTmOA2wblo',
    productId: 'prod_TrUW8GAKEwn5MX',
    color: 'from-amber-500 to-orange-500',
    icon: Crown,
    description: 'Enterprise-grade Web3 infrastructure',
    features: [
      'Everything in Accelerator',
      'Multi-chain deployment',
      'Crypto payment gateway',
      'Custom AI agents for automation',
      'White-label solutions',
      'Compliance & legal guidance',
      'On-demand development team',
      'C-level strategy sessions',
    ],
    deliverables: [
      'Full Web3 ecosystem',
      'Custom blockchain integrations',
      'Revenue automation systems',
      'Quarterly business reviews',
    ],
    guarantee: '50% revenue increase guarantee',
  },
  {
    id: 'partner',
    name: 'Industry Partner',
    tagline: 'Guaranteed Success',
    price: 9997,
    billing: '/month',
    priceId: 'price_1StlXUFjshJghowTKQJcAl8U',
    productId: 'prod_TrUWowzdF6JiXo',
    color: 'from-yellow-400 via-amber-500 to-red-500',
    icon: Diamond,
    elite: true,
    description: 'Full service build + roadmap + auto-execution',
    features: [
      'Everything in Enterprise',
      'Complete done-for-you buildout',
      'AI-powered auto-execution',
      'Guaranteed revenue targets',
      'Equity partnership options',
      'Quarterly in-person strategy',
      'Direct founder access',
      'Priority feature development',
      'Global market expansion',
    ],
    deliverables: [
      'Full ecosystem built & managed',
      'AI army executing 24/7',
      'Guaranteed ROI targets',
      'DAO board seat',
      'Revenue share partnership',
    ],
    guarantee: 'Guaranteed 10x ROI or we work free',
  },
] as const;

export type IndustryTier = typeof INDUSTRY_TIERS[number];
